#!/usr/bin/env python3
"""
Task 0
"""
from pymongo import MongoClient

def list_databases():
    """ Lists all databases """

    client = MongoClient()

    databases = client.list_databases()

    for db in databases:
        print(f"- {db}")

    client.close()

list_databases()
